- README.md
- bower.json
- examples/mapbox-custom-tiles/mapbox-v3.html
- examples/mapbox-custom-tiles/mapbox-v4.html
- package.json
- src/views/map-view.js
https://livefyre.atlassian.net/browse/LF-16747
> LF-16747 - Mapbox v4 support, SSL for map tiles, mapbox examples

- src/map-controller.js
https://livefyre.atlassian.net/browse/LF-17568
> LF-17568: Update keyboard pan/zoom settings based on other values

- bower.json
- package.json
- src/main.js
https://livefyre.atlassian.net/browse/LF-17852
> LF-17852: Check for size of container and modify height if not set

- bower.json
- package.json
- src/map-controller.js
https://livefyre.atlassian.net/browse/LF-18556
> LF-18556: Fix how map sets it's view

- bower.json
- package.json
- src/main.js
- src/util.js
- src/views/map-view.js
Inspired by https://livefyre.atlassian.net/browse/LF-18926
> Use a non-broken non-prod mapId

- bower.json
- package.json
- src/main.js
https://livefyre.atlassian.net/browse/LF-19118
> LF-19118: Fixing issue with non-existent collection

- bower.json
- package.json
- src/views/content-map-view.js
https://livefyre.atlassian.net/browse/LF-20537
Bumping version of SDK to the newest and making supporting change for modals. This fixes the content transforming issue that was causing images to not be displayed properly in the modal.
> LF-20537: Fixing content display issues

- bower.json
- package.json
- src/main.js
- src/util.js
- tests/spec/util.js
https://livefyre.atlassian.net/browse/LF-21230
> LF-21230: Handling map ids and environments better

- bower.json
- package.json
https://livefyre.atlassian.net/browse/LF-19379
> LF-19379 updating sdk to support youtube streams

- bower.json
- package.json
- src/main.js
- src/util.js
- tests/spec/util.js
https://livefyre.atlassian.net/browse/LF-22176
> LF-22176: Fixing map access token issue

- Makefile
- bower.json
- examples/themes/index.html
- package.json
- requirejs.conf.js
- src/main.js
- src/util.js
- src/views/content-map-view.js
- tests/spec/main.js
https://livefyre.atlassian.net/browse/LF-22073
> LF-22073: Updating app-base

- bower.json
- package.json
https://livefyre.atlassian.net/browse/LF-22073
> LF-22073: Bumping SDK version

- bower.json
- package.json
- src/css/style.less
https://livefyre.atlassian.net/browse/LF-21392
> LF-21392: Bumping SDK version

- bower.json
- package.json
https://livefyre.atlassian.net/browse/LF-21392
> LF-21392: Bumping SDK to fix modal content scroll

- bower.json
- package.json
- src/views/content-map-view.js
https://livefyre.atlassian.net/browse/LF-23118
> LF-23118: Fixing duplicate content count issue

- bower.json
- gulpfile.js
- package.json
https://livefyre.atlassian.net/browse/LF-23043
> LF-23043: Bumping SDK for Weibo content

- bower.json
- package.json
- tests/spec/main.js
- tests/spec/map-controller.js
https://livefyre.atlassian.net/browse/LF-23333
https://livefyre.atlassian.net/browse/LF-23500
> Bump SDK version

- .bowerrc
- Jenkinsfile
- bower.json
- gulpfile.js
- package.json
- requirejs.conf.js
- src/css/style.less
- src/map-controller.js
- src/views/content-map-view.js
- src/views/map-view.js
- tests/mocks/streams/MockStream.js
https://jira.corp.adobe.com/browse/FYR-5684
> FYR-5684: Adding DNT support

- bower.json
- package.json
https://jira.corp.adobe.com/browse/FYR-5822
> FYR-5822: Bumping SDK

- bower.json
- package.json
https://jira.corp.adobe.com/browse/FYR-8012
> FYR-8012: Bumping SDK version

- bower.json
- package.json
https://jira.corp.adobe.com/browse/FYR-8094
> FYR-8094: Bumping SDK

- bower.json
- package.json
https://jira.corp.adobe.com/browse/FYR-9167
> FYR-9167: Bump app-base

- bower.json
- package.json
https://jira.corp.adobe.com/browse/FYR-11222
> FYR-11222: Bump SDK

- bower.json
- package.json
https://jira.corp.adobe.com/browse/FYR-9872
> FYR-9872: Bump SDK
